language: node_js
node_js:
  - "10"
script: true
install: 
  - npm install
script:
  - npm run build
branches:
  only:
  - release
env:
  global:
    - VUE_APP_LEANCLOUD_APPKEY=$LEANCLOUD_APPKEY
    - VUE_APP_LEANCLOUD_APPID=$LEANCLOUD_APPID
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  on:
    branch: release