language: node_js
node_js:
  - "10"
script: true
install: 
  - npm install
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: release